class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'hi': {
      'ok': 'ठीक है',
      'farmerBrother': 'किसान भाई',
      'navHome': 'होम',
      'navScan': 'स्कैन',
      'navDocuments': 'दस्तावेज़',
      'navSchemes': 'योजनाएँ',
      'navMore': 'अधिक',
      'chooseLanguage': 'भाषा चुनें',
      'language': 'भाषा',
      'selectedLanguage': 'चुनी गई भाषा',
      'languageChanged': 'भाषा बदल दी गई',
      'todayWeather': 'आज का मौसम',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'wind': 'हवा',
      'weatherUnavailable': 'मौसम जानकारी अभी उपलब्ध नहीं है।',
      'refreshWeather': 'मौसम रीफ्रेश करें',
      'yourLocation': 'आपकी लोकेशन',
      'lastKnownLocation': 'पिछली लोकेशन',
      'defaultLocation': 'डिफ़ॉल्ट स्थान',
      'locationOff': 'लोकेशन बंद है',
      'locationPermissionDenied': 'लोकेशन अनुमति नहीं मिली',
      'clearSky': 'साफ आसमान',
      'partlyCloudy': 'आंशिक बादल',
      'fog': 'धुंध',
      'rain': 'बारिश',
      'snow': 'बर्फबारी',
      'heavyRain': 'भारी बारिश',
      'storm': 'तूफ़ान',
      'services': 'सेवाएँ',
      'scanDoc': 'स्कैन करें',
      'myDocuments': 'मेरे दस्तावेज़',
      'whatsapp': 'WhatsApp',
      'weather': 'मौसम',
      'news': 'समाचार',
      'helpline': 'हेल्पलाइन',
      'whatsappUpdates': 'WhatsApp अपडेट पाएँ',
      'enable': 'चालू करें',
      'smartSuggestion': 'स्मार्ट सुझाव',
      'farmerNews': 'किसान समाचार',
      'trustedByFarmers': 'लाखों किसानों का भरोसा!',
      'farmSmartly': 'KisanKanoon के साथ स्मार्ट खेती',
      'quickLinks': 'त्वरित लिंक',
      'myServices': 'मेरी सेवाएँ',
      'appInfo': 'ऐप जानकारी',
      'logout': 'लॉगआउट',
    },
    'en': {
      'ok': 'OK',
      'farmerBrother': 'Farmer',
      'navHome': 'Home',
      'navScan': 'Scan',
      'navDocuments': 'Documents',
      'navSchemes': 'Schemes',
      'navMore': 'More',
      'chooseLanguage': 'Choose language',
      'language': 'Language',
      'selectedLanguage': 'Selected language',
      'languageChanged': 'Language changed',
      'todayWeather': 'Today\'s weather',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'weatherUnavailable': 'Weather information is not available right now.',
      'refreshWeather': 'Refresh weather',
      'yourLocation': 'Your location',
      'lastKnownLocation': 'Last known location',
      'defaultLocation': 'Default location',
      'locationOff': 'Location is turned off',
      'locationPermissionDenied': 'Location permission was denied',
      'clearSky': 'Clear sky',
      'partlyCloudy': 'Partly cloudy',
      'fog': 'Fog',
      'rain': 'Rain',
      'snow': 'Snow',
      'heavyRain': 'Heavy rain',
      'storm': 'Storm',
      'services': 'Services',
      'scanDoc': 'Scan',
      'myDocuments': 'My Documents',
      'whatsapp': 'WhatsApp',
      'weather': 'Weather',
      'news': 'News',
      'helpline': 'Helpline',
      'whatsappUpdates': 'Get WhatsApp updates',
      'enable': 'Enable',
      'smartSuggestion': 'Smart Suggestion',
      'farmerNews': 'Farmer News',
      'trustedByFarmers': 'Trusted by lakhs of farmers!',
      'farmSmartly': 'Farm smartly with KisanKanoon',
      'quickLinks': 'Quick Links',
      'myServices': 'My Services',
      'appInfo': 'App Info',
      'logout': 'Logout',
    },
    'mr': {
      'ok': 'ठीक आहे',
      'farmerBrother': 'शेतकरी भाऊ',
      'navHome': 'होम',
      'navScan': 'स्कॅन',
      'navDocuments': 'कागदपत्रे',
      'navSchemes': 'योजना',
      'navMore': 'अधिक',
      'chooseLanguage': 'भाषा निवडा',
      'language': 'भाषा',
      'selectedLanguage': 'निवडलेली भाषा',
      'languageChanged': 'भाषा बदलली',
      'todayWeather': 'आजचे हवामान',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'wind': 'वारा',
      'weatherUnavailable': 'हवामान माहिती सध्या उपलब्ध नाही.',
      'refreshWeather': 'हवामान रीफ्रेश करा',
      'yourLocation': 'तुमचे स्थान',
      'lastKnownLocation': 'मागील स्थान',
      'defaultLocation': 'डीफॉल्ट स्थान',
      'locationOff': 'लोकेशन बंद आहे',
      'locationPermissionDenied': 'लोकेशन परवानगी मिळाली नाही',
      'clearSky': 'स्वच्छ आकाश',
      'partlyCloudy': 'अंशतः ढगाळ',
      'fog': 'धुके',
      'rain': 'पाऊस',
      'snow': 'हिमवृष्टी',
      'heavyRain': 'मुसळधार पाऊस',
      'storm': 'वादळ',
      'services': 'सेवा',
      'scanDoc': 'स्कॅन करा',
      'myDocuments': 'माझी कागदपत्रे',
      'whatsapp': 'WhatsApp',
      'weather': 'हवामान',
      'news': 'बातम्या',
      'helpline': 'हेल्पलाइन',
      'whatsappUpdates': 'WhatsApp अपडेट मिळवा',
      'enable': 'सुरू करा',
      'smartSuggestion': 'स्मार्ट सूचना',
      'farmerNews': 'शेतकरी बातम्या',
      'trustedByFarmers': 'लाखो शेतकऱ्यांचा विश्वास!',
      'farmSmartly': 'KisanKanoon सोबत स्मार्ट शेती करा',
      'quickLinks': 'झटपट लिंक',
      'myServices': 'माझ्या सेवा',
      'appInfo': 'अॅप माहिती',
      'logout': 'लॉगआउट',
    },
    'pa': {
      'ok': 'ਠੀਕ ਹੈ',
      'farmerBrother': 'ਕਿਸਾਨ ਵੀਰ',
      'navHome': 'ਹੋਮ',
      'navScan': 'ਸਕੈਨ',
      'navDocuments': 'ਦਸਤਾਵੇਜ਼',
      'navSchemes': 'ਯੋਜਨਾਵਾਂ',
      'navMore': 'ਹੋਰ',
      'chooseLanguage': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'language': 'ਭਾਸ਼ਾ',
      'selectedLanguage': 'ਚੁਣੀ ਭਾਸ਼ਾ',
      'languageChanged': 'ਭਾਸ਼ਾ ਬਦਲ ਦਿੱਤੀ ਗਈ',
      'todayWeather': 'ਅੱਜ ਦਾ ਮੌਸਮ',
      'temperature': 'ਤਾਪਮਾਨ',
      'humidity': 'ਨਮੀ',
      'wind': 'ਹਵਾ',
      'weatherUnavailable': 'ਮੌਸਮ ਜਾਣਕਾਰੀ ਇਸ ਵੇਲੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      'refreshWeather': 'ਮੌਸਮ ਰਿਫ੍ਰੈਸ਼ ਕਰੋ',
      'yourLocation': 'ਤੁਹਾਡੀ ਲੋਕੇਸ਼ਨ',
      'lastKnownLocation': 'ਪਿਛਲੀ ਲੋਕੇਸ਼ਨ',
      'defaultLocation': 'ਡਿਫਾਲਟ ਸਥਾਨ',
      'locationOff': 'ਲੋਕੇਸ਼ਨ ਬੰਦ ਹੈ',
      'locationPermissionDenied': 'ਲੋਕੇਸ਼ਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ',
      'clearSky': 'ਸਾਫ਼ ਅਸਮਾਨ',
      'partlyCloudy': 'ਹਲਕੇ ਬੱਦਲ',
      'fog': 'ਧੁੰਦ',
      'rain': 'ਮੀਂਹ',
      'snow': 'ਬਰਫ਼ਬਾਰੀ',
      'heavyRain': 'ਭਾਰੀ ਮੀਂਹ',
      'storm': 'ਤੂਫ਼ਾਨ',
      'services': 'ਸੇਵਾਵਾਂ',
      'scanDoc': 'ਸਕੈਨ ਕਰੋ',
      'myDocuments': 'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',
      'whatsapp': 'WhatsApp',
      'weather': 'ਮੌਸਮ',
      'news': 'ਖ਼ਬਰਾਂ',
      'helpline': 'ਹੈਲਪਲਾਈਨ',
      'whatsappUpdates': 'WhatsApp ਅਪਡੇਟ ਲਵੋ',
      'enable': 'ਚਾਲੂ ਕਰੋ',
      'smartSuggestion': 'ਸਮਾਰਟ ਸੁਝਾਅ',
      'farmerNews': 'ਕਿਸਾਨ ਖ਼ਬਰਾਂ',
      'trustedByFarmers': 'ਲੱਖਾਂ ਕਿਸਾਨਾਂ ਦਾ ਭਰੋਸਾ!',
      'farmSmartly': 'KisanKanoon ਨਾਲ ਸਮਾਰਟ ਖੇਤੀ ਕਰੋ',
      'quickLinks': 'ਤੁਰੰਤ ਲਿੰਕ',
      'myServices': 'ਮੇਰੀਆਂ ਸੇਵਾਵਾਂ',
      'appInfo': 'ਐਪ ਜਾਣਕਾਰੀ',
      'logout': 'ਲਾਗਆਊਟ',
    },
    'te': {
      'ok': 'సరే',
      'farmerBrother': 'రైతు అన్న',
      'navHome': 'హోమ్',
      'navScan': 'స్కాన్',
      'navDocuments': 'పత్రాలు',
      'navSchemes': 'పథకాలు',
      'navMore': 'మరిన్ని',
      'chooseLanguage': 'భాష ఎంచుకోండి',
      'language': 'భాష',
      'selectedLanguage': 'ఎంచుకున్న భాష',
      'languageChanged': 'భాష మార్చబడింది',
      'todayWeather': 'ఈరోజు వాతావరణం',
      'temperature': 'ఉష్ణోగ్రత',
      'humidity': 'ఆర్ద్రత',
      'wind': 'గాలి',
      'weatherUnavailable': 'వాతావరణ సమాచారం ప్రస్తుతం అందుబాటులో లేదు.',
      'refreshWeather': 'వాతావరణాన్ని రిఫ్రెష్ చేయండి',
      'yourLocation': 'మీ లొకేషన్',
      'lastKnownLocation': 'గత లొకేషన్',
      'defaultLocation': 'డిఫాల్ట్ స్థానం',
      'locationOff': 'లొకేషన్ ఆఫ్‌లో ఉంది',
      'locationPermissionDenied': 'లొకేషన్ అనుమతి లభించలేదు',
      'clearSky': 'స్పష్టమైన ఆకాశం',
      'partlyCloudy': 'భాగంగా మేఘావృతం',
      'fog': 'మంచు',
      'rain': 'వర్షం',
      'snow': 'మంచు వర్షం',
      'heavyRain': 'భారీ వర్షం',
      'storm': 'తుఫాను',
      'services': 'సేవలు',
      'scanDoc': 'స్కాన్ చేయండి',
      'myDocuments': 'నా పత్రాలు',
      'whatsapp': 'WhatsApp',
      'weather': 'వాతావరణం',
      'news': 'వార్తలు',
      'helpline': 'హెల్ప్‌లైన్',
      'whatsappUpdates': 'WhatsApp అప్‌డేట్‌లు పొందండి',
      'enable': 'ఆన్ చేయండి',
      'smartSuggestion': 'స్మార్ట్ సూచన',
      'farmerNews': 'రైతు వార్తలు',
      'trustedByFarmers': 'లక్షలాది రైతుల నమ్మకం!',
      'farmSmartly': 'KisanKanoon తో స్మార్ట్‌గా సాగు చేయండి',
      'quickLinks': 'త్వరిత లింకులు',
      'myServices': 'నా సేవలు',
      'appInfo': 'యాప్ సమాచారం',
      'logout': 'లాగౌట్',
    },
    'bn': {
      'ok': 'ঠিক আছে',
      'farmerBrother': 'কৃষক ভাই',
      'navHome': 'হোম',
      'navScan': 'স্ক্যান',
      'navDocuments': 'নথি',
      'navSchemes': 'স্কিম',
      'navMore': 'আরও',
      'chooseLanguage': 'ভাষা বেছে নিন',
      'language': 'ভাষা',
      'selectedLanguage': 'নির্বাচিত ভাষা',
      'languageChanged': 'ভাষা পরিবর্তন হয়েছে',
      'todayWeather': 'আজকের আবহাওয়া',
      'temperature': 'তাপমাত্রা',
      'humidity': 'আর্দ্রতা',
      'wind': 'বাতাস',
      'weatherUnavailable': 'আবহাওয়ার তথ্য এখন পাওয়া যাচ্ছে না।',
      'refreshWeather': 'আবহাওয়া রিফ্রেশ করুন',
      'yourLocation': 'আপনার অবস্থান',
      'lastKnownLocation': 'শেষ জানা অবস্থান',
      'defaultLocation': 'ডিফল্ট স্থান',
      'locationOff': 'লোকেশন বন্ধ আছে',
      'locationPermissionDenied': 'লোকেশন অনুমতি পাওয়া যায়নি',
      'clearSky': 'পরিষ্কার আকাশ',
      'partlyCloudy': 'আংশিক মেঘলা',
      'fog': 'কুয়াশা',
      'rain': 'বৃষ্টি',
      'snow': 'তুষারপাত',
      'heavyRain': 'ভারী বৃষ্টি',
      'storm': 'ঝড়',
      'services': 'সেবা',
      'scanDoc': 'স্ক্যান করুন',
      'myDocuments': 'আমার নথি',
      'whatsapp': 'WhatsApp',
      'weather': 'আবহাওয়া',
      'news': 'খবর',
      'helpline': 'হেল্পলাইন',
      'whatsappUpdates': 'WhatsApp আপডেট পান',
      'enable': 'চালু করুন',
      'smartSuggestion': 'স্মার্ট পরামর্শ',
      'farmerNews': 'কৃষক সংবাদ',
      'trustedByFarmers': 'লক্ষ কৃষকের ভরসা!',
      'farmSmartly': 'KisanKanoon এর সাথে স্মার্ট চাষ করুন',
      'quickLinks': 'দ্রুত লিংক',
      'myServices': 'আমার সেবা',
      'appInfo': 'অ্যাপ তথ্য',
      'logout': 'লগআউট',
    },
  };

  static String t(String languageCode, String key) {
    return _strings[languageCode]?[key] ?? _strings['hi']?[key] ?? key;
  }

  static String weatherDescription(String languageCode, int code) {
    if (code == 0) return t(languageCode, 'clearSky');
    if (code <= 3) return t(languageCode, 'partlyCloudy');
    if (code <= 48) return t(languageCode, 'fog');
    if (code <= 67) return t(languageCode, 'rain');
    if (code <= 77) return t(languageCode, 'snow');
    if (code <= 82) return t(languageCode, 'heavyRain');
    return t(languageCode, 'storm');
  }

  static String languageChangedMessage(
      String languageCode, String languageName) {
    return '${t(languageCode, 'languageChanged')}: $languageName';
  }
}
