class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'hi': {
      'ok': 'ठीक है',
      'farmerBrother': 'किसान भाई',
      'navHome': 'होम',
      'navScan': 'स्कैन',
      'navDocuments': 'दस्तावेज़',
      'navSchemes': 'योजनाएँ',
      'navMore': 'अधिक',
      'chooseLanguage': 'भाषा चुनें',
      'language': 'भाषा',
      'selectedLanguage': 'चुनी गई भाषा',
      'languageChanged': 'भाषा बदल दी गई',
      'todayWeather': 'आज का मौसम',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'wind': 'हवा',
      'weatherUnavailable': 'मौसम जानकारी अभी उपलब्ध नहीं है।',
      'refreshWeather': 'मौसम रीफ्रेश करें',
      'yourLocation': 'आपकी लोकेशन',
      'lastKnownLocation': 'पिछली लोकेशन',
      'defaultLocation': 'डिफ़ॉल्ट स्थान',
      'locationOff': 'लोकेशन बंद है',
      'locationPermissionDenied': 'लोकेशन अनुमति नहीं मिली',
      'clearSky': 'साफ आसमान',
      'partlyCloudy': 'आंशिक बादल',
      'fog': 'धुंध',
      'rain': 'बारिश',
      'snow': 'बर्फबारी',
      'heavyRain': 'भारी बारिश',
      'storm': 'तूफ़ान',
      'services': 'सेवाएँ',
      'scanDoc': 'स्कैन करें',
      'myDocuments': 'मेरे दस्तावेज़',
      'whatsapp': 'WhatsApp',
      'weather': 'मौसम',
      'news': 'समाचार',
      'helpline': 'हेल्पलाइन',
      'whatsappUpdates': 'WhatsApp अपडेट पाएँ',
      'enable': 'चालू करें',
      'smartSuggestion': 'स्मार्ट सुझाव',
      'farmerNews': 'किसान समाचार',
      'trustedByFarmers': 'लाखों किसानों का भरोसा!',
      'farmSmartly': 'Agri-Shield के साथ स्मार्ट खेती',
      'quickLinks': 'त्वरित लिंक',
      'myServices': 'मेरी सेवाएँ',
      'appInfo': 'ऐप जानकारी',
      'logout': 'लॉगआउट',
    },
    'en': {
      'ok': 'OK',
      'farmerBrother': 'Farmer',
      'navHome': 'Home',
      'navScan': 'Scan',
      'navDocuments': 'Documents',
      'navSchemes': 'Schemes',
      'navMore': 'More',
      'chooseLanguage': 'Choose language',
      'language': 'Language',
      'selectedLanguage': 'Selected language',
      'languageChanged': 'Language changed',
      'todayWeather': 'Today\'s weather',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'weatherUnavailable': 'Weather information is not available right now.',
      'refreshWeather': 'Refresh weather',
      'yourLocation': 'Your location',
      'lastKnownLocation': 'Last known location',
      'defaultLocation': 'Default location',
      'locationOff': 'Location is turned off',
      'locationPermissionDenied': 'Location permission was denied',
      'clearSky': 'Clear sky',
      'partlyCloudy': 'Partly cloudy',
      'fog': 'Fog',
      'rain': 'Rain',
      'snow': 'Snow',
      'heavyRain': 'Heavy rain',
      'storm': 'Storm',
      'services': 'Services',
      'scanDoc': 'Scan',
      'myDocuments': 'My Documents',
      'whatsapp': 'WhatsApp',
      'weather': 'Weather',
      'news': 'News',
      'helpline': 'Helpline',
      'whatsappUpdates': 'Get WhatsApp updates',
      'enable': 'Enable',
      'smartSuggestion': 'Smart Suggestion',
      'farmerNews': 'Farmer News',
      'trustedByFarmers': 'Trusted by lakhs of farmers!',
      'farmSmartly': 'Farm smartly with Agri-Shield',
      'quickLinks': 'Quick Links',
      'myServices': 'My Services',
      'appInfo': 'App Info',
      'logout': 'Logout',
    },
    'mr': {
      'ok': 'ठीक आहे',
      'farmerBrother': 'शेतकरी भाऊ',
      'navHome': 'होम',
      'navScan': 'स्कॅन',
      'navDocuments': 'कागदपत्रे',
      'navSchemes': 'योजना',
      'navMore': 'अधिक',
      'chooseLanguage': 'भाषा निवडा',
      'language': 'भाषा',
      'selectedLanguage': 'निवडलेली भाषा',
      'languageChanged': 'भाषा बदलली',
      'todayWeather': 'आजचे हवामान',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'wind': 'वारा',
      'weatherUnavailable': 'हवामान माहिती सध्या उपलब्ध नाही.',
      'refreshWeather': 'हवामान रीफ्रेश करा',
      'yourLocation': 'तुमचे स्थान',
      'lastKnownLocation': 'मागील स्थान',
      'defaultLocation': 'डीफॉल्ट स्थान',
      'locationOff': 'लोकेशन बंद आहे',
      'locationPermissionDenied': 'लोकेशन परवानगी मिळाली नाही',
      'clearSky': 'स्वच्छ आकाश',
      'partlyCloudy': 'अंशतः ढगाळ',
      'fog': 'धुके',
      'rain': 'पाऊस',
      'snow': 'हिमवृष्टी',
      'heavyRain': 'मुसळधार पाऊस',
      'storm': 'वादळ',
      'services': 'सेवा',
      'scanDoc': 'स्कॅन करा',
      'myDocuments': 'माझी कागदपत्रे',
      'whatsapp': 'WhatsApp',
      'weather': 'हवामान',
      'news': 'बातम्या',
      'helpline': 'हेल्पलाइन',
      'whatsappUpdates': 'WhatsApp अपडेट मिळवा',
      'enable': 'सुरू करा',
      'smartSuggestion': 'स्मार्ट सूचना',
      'farmerNews': 'शेतकरी बातम्या',
      'trustedByFarmers': 'लाखो शेतकऱ्यांचा विश्वास!',
      'farmSmartly': 'Agri-Shield सोबत स्मार्ट शेती करा',
      'quickLinks': 'झटपट लिंक',
      'myServices': 'माझ्या सेवा',
      'appInfo': 'अॅप माहिती',
      'logout': 'लॉगआउट',
    },
    'pa': {
      'ok': 'ਠੀਕ ਹੈ',
      'farmerBrother': 'ਕਿਸਾਨ ਵੀਰ',
      'navHome': 'ਹੋਮ',
      'navScan': 'ਸਕੈਨ',
      'navDocuments': 'ਦਸਤਾਵੇਜ਼',
      'navSchemes': 'ਯੋਜਨਾਵਾਂ',
      'navMore': 'ਹੋਰ',
      'chooseLanguage': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'language': 'ਭਾਸ਼ਾ',
      'selectedLanguage': 'ਚੁਣੀ ਭਾਸ਼ਾ',
      'languageChanged': 'ਭਾਸ਼ਾ ਬਦਲ ਦਿੱਤੀ ਗਈ',
      'todayWeather': 'ਅੱਜ ਦਾ ਮੌਸਮ',
      'temperature': 'ਤਾਪਮਾਨ',
      'humidity': 'ਨਮੀ',
      'wind': 'ਹਵਾ',
      'weatherUnavailable': 'ਮੌਸਮ ਜਾਣਕਾਰੀ ਇਸ ਵੇਲੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      'refreshWeather': 'ਮੌਸਮ ਰਿਫ੍ਰੈਸ਼ ਕਰੋ',
      'yourLocation': 'ਤੁਹਾਡੀ ਲੋਕੇਸ਼ਨ',
      'lastKnownLocation': 'ਪਿਛਲੀ ਲੋਕੇਸ਼ਨ',
      'defaultLocation': 'ਡਿਫਾਲਟ ਸਥਾਨ',
      'locationOff': 'ਲੋਕੇਸ਼ਨ ਬੰਦ ਹੈ',
      'locationPermissionDenied': 'ਲੋਕੇਸ਼ਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ',
      'clearSky': 'ਸਾਫ਼ ਅਸਮਾਨ',
      'partlyCloudy': 'ਹਲਕੇ ਬੱਦਲ',
      'fog': 'ਧੁੰਦ',
      'rain': 'ਮੀਂਹ',
      'snow': 'ਬਰਫ਼ਬਾਰੀ',
      'heavyRain': 'ਭਾਰੀ ਮੀਂਹ',
      'storm': 'ਤੂਫ਼ਾਨ',
      'services': 'ਸੇਵਾਵਾਂ',
      'scanDoc': 'ਸਕੈਨ ਕਰੋ',
      'myDocuments': 'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',
      'whatsapp': 'WhatsApp',
      'weather': 'ਮੌਸਮ',
      'news': 'ਖ਼ਬਰਾਂ',
      'helpline': 'ਹੈਲਪਲਾਈਨ',
      'whatsappUpdates': 'WhatsApp ਅਪਡੇਟ ਲਵੋ',
      'enable': 'ਚਾਲੂ ਕਰੋ',
      'smartSuggestion': 'ਸਮਾਰਟ ਸੁਝਾਅ',
      'farmerNews': 'ਕਿਸਾਨ ਖ਼ਬਰਾਂ',
      'trustedByFarmers': 'ਲੱਖਾਂ ਕਿਸਾਨਾਂ ਦਾ ਭਰੋਸਾ!',
      'farmSmartly': 'Agri-Shield ਨਾਲ ਸਮਾਰਟ ਖੇਤੀ ਕਰੋ',
      'quickLinks': 'ਤੁਰੰਤ ਲਿੰਕ',
      'myServices': 'ਮੇਰੀਆਂ ਸੇਵਾਵਾਂ',
      'appInfo': 'ਐਪ ਜਾਣਕਾਰੀ',
      'logout': 'ਲਾਗਆਊਟ',
    },
    'te': {
      'ok': 'సరే',
      'farmerBrother': 'రైతు అన్న',
      'navHome': 'హోమ్',
      'navScan': 'స్కాన్',
      'navDocuments': 'పత్రాలు',
      'navSchemes': 'పథకాలు',
      'navMore': 'మరిన్ని',
      'chooseLanguage': 'భాష ఎంచుకోండి',
      'language': 'భాష',
      'selectedLanguage': 'ఎంచుకున్న భాష',
      'languageChanged': 'భాష మార్చబడింది',
      'todayWeather': 'ఈరోజు వాతావరణం',
      'temperature': 'ఉష్ణోగ్రత',
      'humidity': 'ఆర్ద్రత',
      'wind': 'గాలి',
      'weatherUnavailable': 'వాతావరణ సమాచారం ప్రస్తుతం అందుబాటులో లేదు.',
      'refreshWeather': 'వాతావరణాన్ని రిఫ్రెష్ చేయండి',
      'yourLocation': 'మీ లొకేషన్',
      'lastKnownLocation': 'గత లొకేషన్',
      'defaultLocation': 'డిఫాల్ట్ స్థానం',
      'locationOff': 'లొకేషన్ ఆఫ్‌లో ఉంది',
      'locationPermissionDenied': 'లొకేషన్ అనుమతి లభించలేదు',
      'clearSky': 'స్పష్టమైన ఆకాశం',
      'partlyCloudy': 'భాగంగా మేఘావృతం',
      'fog': 'మంచు',
      'rain': 'వర్షం',
      'snow': 'మంచు వర్షం',
      'heavyRain': 'భారీ వర్షం',
      'storm': 'తుఫాను',
      'services': 'సేవలు',
      'scanDoc': 'స్కాన్ చేయండి',
      'myDocuments': 'నా పత్రాలు',
      'whatsapp': 'WhatsApp',
      'weather': 'వాతావరణం',
      'news': 'వార్తలు',
      'helpline': 'హెల్ప్‌లైన్',
      'whatsappUpdates': 'WhatsApp అప్‌డేట్‌లు పొందండి',
      'enable': 'ఆన్ చేయండి',
      'smartSuggestion': 'స్మార్ట్ సూచన',
      'farmerNews': 'రైతు వార్తలు',
      'trustedByFarmers': 'లక్షలాది రైతుల నమ్మకం!',
      'farmSmartly': 'Agri-Shield తో స్మార్ట్‌గా సాగు చేయండి',
      'quickLinks': 'త్వరిత లింకులు',
      'myServices': 'నా సేవలు',
      'appInfo': 'యాప్ సమాచారం',
      'logout': 'లాగౌట్',
    },
    'bn': {
      'ok': 'ঠিক আছে',
      'farmerBrother': 'কৃষক ভাই',
      'navHome': 'হোম',
      'navScan': 'স্ক্যান',
      'navDocuments': 'নথি',
      'navSchemes': 'স্কিম',
      'navMore': 'আরও',
      'chooseLanguage': 'ভাষা বেছে নিন',
      'language': 'ভাষা',
      'selectedLanguage': 'নির্বাচিত ভাষা',
      'languageChanged': 'ভাষা পরিবর্তন হয়েছে',
      'todayWeather': 'আজকের আবহাওয়া',
      'temperature': 'তাপমাত্রা',
      'humidity': 'আর্দ্রতা',
      'wind': 'বাতাস',
      'weatherUnavailable': 'আবহাওয়ার তথ্য এখন পাওয়া যাচ্ছে না।',
      'refreshWeather': 'আবহাওয়া রিফ্রেশ করুন',
      'yourLocation': 'আপনার অবস্থান',
      'lastKnownLocation': 'শেষ জানা অবস্থান',
      'defaultLocation': 'ডিফল্ট স্থান',
      'locationOff': 'লোকেশন বন্ধ আছে',
      'locationPermissionDenied': 'লোকেশন অনুমতি পাওয়া যায়নি',
      'clearSky': 'পরিষ্কার আকাশ',
      'partlyCloudy': 'আংশিক মেঘলা',
      'fog': 'কুয়াশা',
      'rain': 'বৃষ্টি',
      'snow': 'তুষারপাত',
      'heavyRain': 'ভারী বৃষ্টি',
      'storm': 'ঝড়',
      'services': 'সেবা',
      'scanDoc': 'স্ক্যান করুন',
      'myDocuments': 'আমার নথি',
      'whatsapp': 'WhatsApp',
      'weather': 'আবহাওয়া',
      'news': 'খবর',
      'helpline': 'হেল্পলাইন',
      'whatsappUpdates': 'WhatsApp আপডেট পান',
      'enable': 'চালু করুন',
      'smartSuggestion': 'স্মার্ট পরামর্শ',
      'farmerNews': 'কৃষক সংবাদ',
      'trustedByFarmers': 'লক্ষ কৃষকের ভরসা!',
      'farmSmartly': 'Agri-Shield এর সাথে স্মার্ট চাষ করুন',
      'quickLinks': 'দ্রুত লিংক',
      'myServices': 'আমার সেবা',
      'appInfo': 'অ্যাপ তথ্য',
      'logout': 'লগআউট',
    },
  };

  static const Map<String, Map<String, String>> _extraStrings = {
    'hi': {
      'scanDocumentTitle': 'दस्तावेज़ स्कैन करें',
      'scanOrUploadDocument': 'दस्तावेज़ स्कैन या अपलोड करें',
      'reviewAndAddDetails':
          'स्कैन या अपलोड के बाद दस्तावेज़ की जानकारी खुद भरें।',
      'camera': 'कैमरा',
      'uploadImage': 'फोटो अपलोड करें',
      'uploadPdfDocument': 'PDF / दस्तावेज़ अपलोड करें',
      'selectedFile': 'चयनित फ़ाइल',
      'pickDocumentFailed': 'दस्तावेज़ चुना नहीं जा सका। फिर से कोशिश करें।',
      'documentDetails': 'दस्तावेज़ विवरण',
      'onlyEnteredDetailsSaved':
          'सिर्फ वही जानकारी सेव होगी जो आप यहां भरेंगे।',
      'documentName': 'दस्तावेज़ का नाम',
      'documentNameHint': 'उदाहरण: जमीन रजिस्ट्री 2026',
      'documentType': 'दस्तावेज़ प्रकार',
      'selectDocumentType': 'दस्तावेज़ प्रकार चुनें',
      'documentIdNumber': 'दस्तावेज़ आईडी / नंबर',
      'documentIdHint': 'उदाहरण: 452/3 या ABCD1234',
      'notesLabel': 'नोट्स',
      'notesHint': 'दस्तावेज़ से जुड़ी अतिरिक्त जानकारी लिखें',
      'saveDocument': 'दस्तावेज़ सुरक्षित करें',
      'saving': 'सेव हो रहा है...',
      'newScan': 'नया स्कैन',
      'firebaseSyncNote':
          'सेव करने पर फ़ाइल आपके डिवाइस में रहेगी और Firestore खाते में सिंक करने की कोशिश होगी।',
      'supportedDocuments': 'समर्थित दस्तावेज़',
      'pleaseEnterDocumentName': 'सेव करने से पहले दस्तावेज़ का नाम लिखें।',
      'pleaseChooseDocumentType': 'सेव करने से पहले दस्तावेज़ का प्रकार चुनें।',
      'documentSavedSynced': 'दस्तावेज़ सेव हो गया और Firebase से सिंक हो गया।',
      'documentSavedMetadataOnly':
          'दस्तावेज़ सेव हो गया। Firebase में विवरण सिंक हो गया, लेकिन फ़ाइल बड़ी होने के कारण केवल इस डिवाइस में रखी गई है।',
      'documentSavedPending':
          'दस्तावेज़ इस डिवाइस में सेव हो गया, Firebase सिंक बाकी है।',
      'documentSavedSyncFailedPrefix':
          'दस्तावेज़ इस डिवाइस में सेव हो गया, लेकिन Firebase सिंक नहीं हो सका: ',
      'documentSaveFailed': 'दस्तावेज़ सेव नहीं हो सका। फिर से कोशिश करें।',
      'deviceAndFirestore': 'डिवाइस + Firestore',
      'noDocumentsYet': 'अभी कोई दस्तावेज़ नहीं है',
      'documentsEmptyHint':
          'स्कैन या अपलोड किया गया दस्तावेज़ यहां अपने आप दिखेगा।',
      'firebaseSynced': 'Firebase सिंक हो गया',
      'firebaseSyncPending': 'Firebase सिंक बाकी',
      'deleteDocumentQuestion': 'दस्तावेज़ हटाएं?',
      'deleteDocumentWarning':
          'यह दस्तावेज़ आपके फ़ोल्डर और Firebase डेटा से हट जाएगा।',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'deleteFailed':
          'दस्तावेज़ Firebase से हटाया नहीं जा सका। फिर से कोशिश करें।',
      'notAdded': 'नहीं जोड़ा गया',
      'firebaseStatus': 'Firebase स्थिति',
      'syncedSuccessfully': 'सफलतापूर्वक सिंक',
      'notSyncedYet': 'अभी सिंक नहीं हुआ',
      'accountId': 'अकाउंट आईडी',
      'syncMessage': 'सिंक संदेश',
      'fileType': 'फ़ाइल प्रकार',
      'savedAt': 'सेव समय',
      'justNow': 'अभी',
      'documentWord': 'दस्तावेज़',
      'generalDocument': 'सामान्य दस्तावेज़',
      'landRecord': 'जमीन रिकॉर्ड',
      'aadhaarCard': 'आधार कार्ड',
      'bankPassbook': 'बैंक पासबुक',
      'registryPaper': 'रजिस्ट्री पेपर',
      'governmentNotice': 'सरकारी नोटिस',
      'courtDocument': 'कोर्ट दस्तावेज़',
      'other': 'अन्य',
      'pdfDocument': 'PDF / दस्तावेज़',
      'fileKeptOnDevice':
          'फ़ाइल बड़ी होने के कारण केवल इस डिवाइस में रखी गई है।',
    },
    'en': {
      'scanDocumentTitle': 'Scan Document',
      'scanOrUploadDocument': 'Scan or upload your document',
      'reviewAndAddDetails':
          'After scan or upload, add the document details yourself.',
      'camera': 'Camera',
      'uploadImage': 'Upload image',
      'uploadPdfDocument': 'Upload PDF / document',
      'selectedFile': 'Selected file',
      'pickDocumentFailed':
          'The document could not be selected. Please try again.',
      'documentDetails': 'Document details',
      'onlyEnteredDetailsSaved':
          'Only the details you enter here will be stored with this document.',
      'documentName': 'Document name',
      'documentNameHint': 'Example: Land registry 2026',
      'documentType': 'Document type',
      'selectDocumentType': 'Select document type',
      'documentIdNumber': 'Document ID / number',
      'documentIdHint': 'Example: 452/3 or ABCD1234',
      'notesLabel': 'Notes',
      'notesHint': 'Add any extra detail about this document',
      'saveDocument': 'Save document',
      'saving': 'Saving...',
      'newScan': 'New scan',
      'firebaseSyncNote':
          'When you save, the file stays on your device and also tries to sync with your Firestore account.',
      'supportedDocuments': 'Supported documents',
      'pleaseEnterDocumentName': 'Please enter a document name before saving.',
      'pleaseChooseDocumentType':
          'Please choose the document type before saving.',
      'documentSavedSynced':
          'Document saved successfully and synced to Firebase.',
      'documentSavedMetadataOnly':
          'Document saved successfully. Firebase synced the details, but the file stays only on this device because it is too large for free sync.',
      'documentSavedPending':
          'Document saved on this device, but Firebase sync is still pending.',
      'documentSavedSyncFailedPrefix':
          'Document saved on this device, but Firebase sync failed: ',
      'documentSaveFailed': 'Document could not be saved. Please try again.',
      'deviceAndFirestore': 'Device + Firestore',
      'noDocumentsYet': 'No documents yet',
      'documentsEmptyHint':
          'A scanned or uploaded document will appear here automatically.',
      'firebaseSynced': 'Firebase synced',
      'firebaseSyncPending': 'Firebase sync pending',
      'deleteDocumentQuestion': 'Delete document?',
      'deleteDocumentWarning':
          'This will remove the document from your folder and Firebase data.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleteFailed':
          'The document could not be deleted from Firebase. Please try again.',
      'notAdded': 'Not added',
      'firebaseStatus': 'Firebase status',
      'syncedSuccessfully': 'Synced successfully',
      'notSyncedYet': 'Not synced yet',
      'accountId': 'Account ID',
      'syncMessage': 'Sync message',
      'fileType': 'File type',
      'savedAt': 'Saved at',
      'justNow': 'Just now',
      'documentWord': 'Document',
      'generalDocument': 'General document',
      'landRecord': 'Land Record',
      'aadhaarCard': 'Aadhaar Card',
      'bankPassbook': 'Bank Passbook',
      'registryPaper': 'Registry Paper',
      'governmentNotice': 'Government Notice',
      'courtDocument': 'Court Document',
      'other': 'Other',
      'pdfDocument': 'PDF / document',
      'fileKeptOnDevice':
          'The file stays only on this device because it is too large for free sync.',
    },
  };

  static String t(String languageCode, String key) {
    return _extraStrings[languageCode]?[key] ??
        _strings[languageCode]?[key] ??
        _extraStrings['hi']?[key] ??
        _strings['hi']?[key] ??
        key;
  }

  static String weatherDescription(String languageCode, int code) {
    if (code == 0) return t(languageCode, 'clearSky');
    if (code <= 3) return t(languageCode, 'partlyCloudy');
    if (code <= 48) return t(languageCode, 'fog');
    if (code <= 67) return t(languageCode, 'rain');
    if (code <= 77) return t(languageCode, 'snow');
    if (code <= 82) return t(languageCode, 'heavyRain');
    return t(languageCode, 'storm');
  }

  static String languageChangedMessage(
      String languageCode, String languageName) {
    return '${t(languageCode, 'languageChanged')}: $languageName';
  }
}
